import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MenuLeft } from '@/sections/root-layout/menu-left';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            border: '1px solid black',
            position: 'absolute',
            top: 0,
            left: '280px',
            width: 'calc(100% - 280px)',
            height: '60px',
          }}
        >
          header
        </div>
        <div
          style={{
            border: '1px solid black',
            position: 'absolute',
            top: 0,
            left: 0,
            width: '280px',
            height: '100vh',
          }}
        >
          <MenuLeft />
        </div>
        <div
          style={{
            position: 'absolute',
            top: '60px',
            left: '280px',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
